version: 1
service: .
cpln:
  org: cpln-git-deploy
  gvc: development
workloads:
  - name: cpln-test-pnp
    type: web
    workload: cpln-test-pnp
    port: 3000
    healthPath: /healthz
    public: true
